# Generated by Django 5.1.5 on 2025-01-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('livreur', 'Livreur')], default='admin', max_length=10),
            preserve_default=False,
        ),
    ]
