# Generated by Django 5.1.5 on 2025-01-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_adresse_alter_user_bank_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
    ]
