# Generated by Django 5.1.5 on 2025-01-24 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id_zone', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=255)),
                ('zone_status', models.BooleanField(default=True)),
            ],
        ),
    ]
