# Generated by Django 5.1.5 on 2025-01-24 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id_colis', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('merchandise', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('adresse', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_replaced', models.BooleanField()),
                ('is_openable', models.BooleanField()),
                ('is_fragile', models.BooleanField()),
            ],
        ),
    ]
