# Generated by Django 5.1.5 on 2025-01-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='etat',
            field=models.CharField(choices=[('1', 'Payé'), ('2', 'Non Payé\t')], default='Non Payé\t', max_length=4),
        ),
    ]
