# Generated by Django 5.1.5 on 2025-01-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0003_parcel_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('1', 'Nouveau Colis'), ('2', 'Attente De Ramassage'), ('3', 'Ramassé'), ('4', 'Expédié'), ('5', 'Reçu'), ('6', 'Mise en distribution'), ('7', 'In progress'), ('8', 'Livré'), ('9', 'Retourné')], default='Non Payé\t', max_length=4),
        ),
    ]
