# Generated by Django 5.1.5 on 2025-01-31 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_initial'),
        ('parcel', '0005_remove_parcel_zone_parcel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_zone', to='city.city'),
        ),
    ]
