# Generated by Django 5.1.5 on 2025-01-24 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personalised_price',
            fields=[
                ('id_personalised_price', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
