# Generated by Django 5.1.5 on 2025-01-31 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_remove_city_personalised_price'),
        ('personalised_price', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalised_price',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_personnel_price', to='city.city'),
        ),
    ]
