# Generated by Django 5.1.5 on 2025-01-29 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0002_initial'),
        ('reclamation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='colis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reclamation_colis', to='parcel.parcel'),
            preserve_default=False,
        ),
    ]
