# Generated by Django 5.1.5 on 2025-01-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delevery_document', '0001_initial'),
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleverydocument',
            name='parcel',
            field=models.ManyToManyField(related_name='delevery_parcel', to='parcel.parcel'),
        ),
    ]
