# Generated by Django 5.1.5 on 2025-01-24 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
        ('personalised_price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='Personalised_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalised_price.personalised_price'),
        ),
    ]
