# Generated by Django 5.1.5 on 2025-01-31 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='Personalised_price',
        ),
    ]
