# Generated by Django 5.1.5 on 2025-01-24 16:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUp',
            fields=[
                ('id_pickup', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_parcel', to='parcel.parcel')),
            ],
        ),
    ]
